npm install --global bower
npm install --global browserify
npm install --global coffee-script
npm install --global grunt-cli
npm install --global gulp
npm install --global http-server
npm install --global jshint
npm install --global jspm
npm install --global karma-cli
npm install --global less
npm install --global live-server
npm install --global mocha
npm install --global psi
npm install --global stylestats
npm install --global yuidocjs
