brew cask install airfoil
brew cask install caffeine
brew cask install divvy
brew cask install dropbox
brew cask install google-chrome
brew cask install macvim
brew cask install onepassword
brew cask install rdio
brew cask install screenhero
brew cask install slack
brew cask install transmission
brew cask install transmit
brew cask install vagrant
brew cask install virtualbox
brew cask install vlc
brew cask install ynab
