brew cask install 1password
brew cask install adobe-creative-cloud
brew cask install adobe-photoshop-cc
brew cask install airfoil
brew cask install caffeine
brew cask install cloud
brew cask install divvy
brew cask install dropbox
brew cask install google-chrome
brew cask install google-drive
brew cask install macvim
brew cask install slack
brew cask install sonos
brew cask install spotify
brew cask install superduper
brew cask install transmission
brew cask install vagrant
brew cask install virtualbox
brew cask install vlc
brew cask install ynab
