brew install ack
brew install brew-cask
brew install direnv
brew install git
brew install git-extras
brew install gitsh
brew install heroku-toolbelt
brew install imagemagick
brew install node
brew install packer
brew install postgresql
brew install rbenv
brew install rbenv-gem-rehash
brew install reattach-to-user-namespace
brew install ruby-build
brew install ssh-copy-id
brew install the_silver_searcher
brew install tmux
brew install tree
brew install vim
brew install wget
brew install zsh
