brew install ack
brew install brew-cask
brew install dockutil
brew install git
brew install git-extras
brew install gitsh
brew install go
brew install heroku-toolbelt
brew install httpie
brew install hub
brew install imagemagick
brew install node
brew install postgresql
brew install rbenv
brew install reattach-to-user-namespace
brew install ruby-build
brew install ssh-copy-id
brew install the_silver_searcher
brew install tig
brew install tmux
brew install tree
brew install vim
brew install wget
brew install zsh
